Algoritmo " contador_faça Enquanto "
// Função: Este algoritmo conta de 0 até 30 com incremento de 3 utilizando a estrutura de repetição faça-enquanto.
// Autor: Victor Martins
// Data: 04/10/2023

// Seção de Declarações
Var
c: inteiro

Inicio
// Inicialização da variável de controle
c <- 0

// Repetição faça-enquanto para contar até 30 com incremento de 3
Repita
   Escreva(c)
   c <- c + 3
Ate (c > 30)

Escreval("Acabou!") // Indica que a contagem terminou
Fimalgoritmo
