Algoritmo "Contador tres em tres"

// Função: Contar de 0 até 18 de 3 em 3
// Autor: Victor Martins
// Data: 28/09/2023

Var
c: Inteiro  // Variável para o contador

Inicio
c <- 0  // Inicializa o contador com 0
Enquanto (c <= 18) faca  // Enquanto o contador for menor ou igual a 18, faça:
   Escreva(c)  // Escreve o valor atual do contador
   c <- c + 3  // Incrementa o contador em 3 para a próxima iteração
FimEnquanto  // Fim do loop enquanto
Escreva("Acabou !")
Fimalgoritmo
